import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Head from "next/head";
import { useActionState, useEffect } from "react";
import { useAppDispatch } from "@/hooks/hooke";
import { getUserAction } from "@/store/actions/auth/getUserAction";
import { useRouter } from "next/router";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // const router = useRouter()
  // const dispatch = useAppDispatch()
  // useEffect(()=>{
  //   const getUser = async ()=>{
  //      const response = await dispatch(getUserAction())
  //      console.log('its from layout', response);
       
  //      if(response?.payload.success){
  //       router.push('/')
  //      }
  //   }
  //   getUser()
  // },[router,dispatch])


  return (
    <html lang="en">
     <Head>
        <link
          rel="preconnect"
          href="https://fonts.googleapis.com"
        />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@400;700&family=Poppins:wght@400;700&family=Titillium+Web:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      
      <body>
        {children}
      </body>
    </html>
  );
}
